<h1 align="center"> Naive Testing </h1>
<h3 align="center"> Christine Zhang </h3>

---

In [23]:
import numpy as np
import pandas as pd
import scipy as sp
import pickle
from sklearn import preprocessing
from sklearn.cross_validation import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.tree import DecisionTreeClassifier as DecisionTree
from sklearn.ensemble import RandomForestClassifier as RandomForest
from sklearn.ensemble import RandomForestClassifier
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import confusion_matrix
import csv
from sklearn.svm import SVC
from sklearn import svm
from sklearn.cross_validation import train_test_split
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [24]:
file_name = "datamaster"
file_object = open(file_name,'r')  
compiled_pd = pickle.load(file_object)
compiled_pd.tail(n=10)

,3,7,10,15,16,19,21,22,23,25,...,155481,155493,155498,155502,155505,155510,155511,155513,155518,155520
Entrez_id,,,,,,,,,,,,,,,,,,,,,
8522.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00
2885.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00
2161.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00
27255.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,1.000,0.000,1.000,0.00,0.00
23072.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,1.000,1.000,0.00,0.00
6725.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00
9149.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00
6241.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00
8301.0,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.00
0.0,2.473,2.142,3.38,3.374,3.123,3.779,3.471,2.625,4.677,2.751,...,2.469,3.071,5.351,3.929,3.912,4.913,3.755,1.712,4.61,5.46

In [27]:
no_auc_pd = compiled_pd.drop(compiled_pd.index[len(compiled_pd)-1])
no_auc_pd.tail(n=10)

,3,7,10,15,16,19,21,22,23,25,...,155481,155493,155498,155502,155505,155510,155511,155513,155518,155520
Entrez_id,,,,,,,,,,,,,,,,,,,,,
6608.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8522.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2885.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2161.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27255.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
23072.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
6725.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9149.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6241.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8301.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
no_auc_trans_pd = no_auc_pd.transpose()
no_auc_trans = no_auc_trans_pd.as_matrix()

In [65]:
auc_pd = compiled_pd.iloc[-1:]
auc = auc_pd.as_matrix()
auc = auc.reshape([472,1])

In [64]:
x_train, x_test, y_train, y_test = train_test_split(no_auc_trans, auc, test_size=0.5, random_state=42)

In [74]:
#Function for computing the accuracy a given model on the entire test set
score = lambda model, x_test, y_test: pd.Series([model.score(x_test, y_test)],
                                                index=['overall accuracy'])

In [77]:
#Unweighted logistic regression
unweighted_logistic = LogisticRegression()
unweighted_logistic.fit(x_train, y_train)
unweighted_log_scores = score(unweighted_logistic, x_test, y_test)

#Unweighted logistic quadratic regression
unweighted_logistic_poly = LogisticRegression()

#Expand our predictor array with quadratic terms
quad_features = preprocessing.PolynomialFeatures(degree = 2)
x_expanded_train = quad_features.fit_transform(x_train)
x_expanded_test = quad_features.fit_transform(x_test)

unweighted_logistic_poly.fit(x_expanded_train, y_train)
unweighted_log_poly_scores = score(unweighted_logistic_poly, x_expanded_test, y_test)

#Weighted logistic regression
weighted_logistic = LogisticRegression(class_weight='balanced')
weighted_logistic.fit(x_train, y_train)
weighted_log_scores = score(weighted_logistic, x_test, y_test)

#Weighted quad logistic regression
weighted_logistic_poly = LogisticRegression(class_weight='balanced')

#Expand our predictor array with quadratic terms
quad_features = preprocessing.PolynomialFeatures(degree = 2)
x_expanded_train = quad_features.fit_transform(x_train)
x_expanded_test = quad_features.fit_transform(x_test)

weighted_logistic_poly.fit(x_expanded_train, y_train)
weighted_log_poly_scores = score(weighted_logistic_poly, x_expanded_test, y_test)

#LDA
lda = LDA()
lda.fit(x_train, y_train)
lda_scores = score(lda, x_test, y_test)

#QDA
qda = QDA()
qda.fit(x_train, y_train)
qda_scores = score(qda, x_test, y_test)

#Random Forest
rf = RandomForest()
rf.fit(x_train, y_train)
rf_scores = score(rf, x_test, y_test)

#SVM
svm = SVC(C=svm_best_depth, kernel='linear', class_weight='balanced')
svm.fit(x_train[1:100], y_train[1:100])
svm_scores = score(svm, x_test, y_test)

/Users/christine/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ValueError: Unknown label type: 'continuous'